M->__ValToPrg_Object := SR_PGS():New()
   M->__ValToPrg_Object:NCONNECTIONTYPE :=          4
   M->__ValToPrg_Object:NSIZEMAXBUFF :=       4000
   M->__ValToPrg_Object:NPREFETCH :=         50
   M->__ValToPrg_Object:COWNER := ""
   M->__ValToPrg_Object:LTRACE := .F.
   M->__ValToPrg_Object:OSQLTRANSACT := SR_PGS():New()
      M->__ValToPrg_Object:OSQLTRANSACT:NSIZEMAXBUFF :=       4000
      M->__ValToPrg_Object:OSQLTRANSACT:NPREFETCH :=         50
      M->__ValToPrg_Object:OSQLTRANSACT:COWNER := ""
      M->__ValToPrg_Object:OSQLTRANSACT:LTRACE := .F.
      M->__ValToPrg_Object:OSQLTRANSACT:NSELMETH :=          0
      M->__ValToPrg_Object:OSQLTRANSACT:NEMPTYMODE :=          0
      M->__ValToPrg_Object:OSQLTRANSACT:NDATEMODE :=          0
      M->__ValToPrg_Object:OSQLTRANSACT:OSQL := M->__ValToPrg_Object:OSQLTRANSACT /* Cyclic */
      M->__ValToPrg_Object:OSQLTRANSACT:USID :=     5652
      M->__ValToPrg_Object:OSQLTRANSACT:CLOCKWAIT := ""
      M->__ValToPrg_Object:OSQLTRANSACT:CTARGETDB := "POSTGRESQL NATIVE"
      M->__ValToPrg_Object:OSQLTRANSACT:CSYSTEMNAME := "PostgreSQL Native"
      M->__ValToPrg_Object:OSQLTRANSACT:NSYSTEMID :=         13
      M->__ValToPrg_Object:OSQLTRANSACT:CSYSTEMVERS := "PostgreSQL 9.1.11, compiled by Visual C++ build 1500, 64-bit"
      M->__ValToPrg_Object:OSQLTRANSACT:NFIELDS :=          1
      M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS := Array(1)
         M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1] := Array(11)
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][1] := "PG_BACKEND_PID"
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][2] := "N"
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][3] :=         11
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][4] :=          0
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][5] := .F.
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][6] :=          2
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][7] := NIL
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][8] :=          1
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][9] := NIL
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][10] := NIL
            M->__ValToPrg_Object:OSQLTRANSACT:AFIELDS[1][11] := NIL


      M->__ValToPrg_Object:OSQLTRANSACT:HDBC := 0x3B611B0
      M->__ValToPrg_Object:OSQLTRANSACT:NRETCODE :=          0
      M->__ValToPrg_Object:OSQLTRANSACT:NVERSION :=          1
      M->__ValToPrg_Object:OSQLTRANSACT:OHASHACTIVEWAS := SQLFASTHASH():New()
         M->__ValToPrg_Object:OSQLTRANSACT:OHASHACTIVEWAS:HHASH := Hash()

      M->__ValToPrg_Object:OSQLTRANSACT:ATABLEINFO := Hash()
      M->__ValToPrg_Object:OSQLTRANSACT:LCOUNTER := .T.
      M->__ValToPrg_Object:OSQLTRANSACT:LRESULTSET := .F.
      M->__ValToPrg_Object:OSQLTRANSACT:CLASTCOMM := "COMMIT
BEGIN"
      M->__ValToPrg_Object:OSQLTRANSACT:OODBC := M->__ValToPrg_Object:OSQLTRANSACT /* Cyclic */
      M->__ValToPrg_Object:OSQLTRANSACT:NMILISECONDS :=          0.00
      M->__ValToPrg_Object:OSQLTRANSACT:CPORT := 5432
      M->__ValToPrg_Object:OSQLTRANSACT:CHOST := "localhost"
      M->__ValToPrg_Object:OSQLTRANSACT:CDBS := ""
      M->__ValToPrg_Object:OSQLTRANSACT:CDRV := ""
      M->__ValToPrg_Object:OSQLTRANSACT:CDTB := "sm"
      M->__ValToPrg_Object:OSQLTRANSACT:CNETLIBRARY := ""

   M->__ValToPrg_Object:NSELMETH :=          0
   M->__ValToPrg_Object:NEMPTYMODE :=          0
   M->__ValToPrg_Object:NDATEMODE :=          0
   M->__ValToPrg_Object:OSQL := M->__ValToPrg_Object /* Cyclic */
   M->__ValToPrg_Object:CSQLERROR := E"(-1) PGRES_FATAL_ERROR - ERRO:  relação \"top_field\" não existe\nLINE 1: ...IELD_NAME, FIELD_TYPE, FIELD_PREC, FIELD_DEC FROM TOP_FIELD ...\n                                                             ^\n"
   M->__ValToPrg_Object:USID :=     4408
   M->__ValToPrg_Object:CLOCKWAIT := ""
   M->__ValToPrg_Object:CTARGETDB := "POSTGRESQL NATIVE"
   M->__ValToPrg_Object:CSYSTEMNAME := "PostgreSQL Native"
   M->__ValToPrg_Object:NSYSTEMID :=         13
   M->__ValToPrg_Object:CSYSTEMVERS := "PostgreSQL 9.1.11, compiled by Visual C++ build 1500, 64-bit"
   M->__ValToPrg_Object:NFIELDS :=          5
   M->__ValToPrg_Object:AFIELDS := Array(5)
      M->__ValToPrg_Object:AFIELDS[1] := Array(11)
         M->__ValToPrg_Object:AFIELDS[1][1] := "TABLE_"
         M->__ValToPrg_Object:AFIELDS[1][2] := "C"
         M->__ValToPrg_Object:AFIELDS[1][3] :=         50
         M->__ValToPrg_Object:AFIELDS[1][4] :=          0
         M->__ValToPrg_Object:AFIELDS[1][5] := .F.
         M->__ValToPrg_Object:AFIELDS[1][6] :=          1
         M->__ValToPrg_Object:AFIELDS[1][7] := NIL
         M->__ValToPrg_Object:AFIELDS[1][8] :=          1
         M->__ValToPrg_Object:AFIELDS[1][9] := NIL
         M->__ValToPrg_Object:AFIELDS[1][10] := NIL
         M->__ValToPrg_Object:AFIELDS[1][11] := NIL

      M->__ValToPrg_Object:AFIELDS[2] := Array(11)
         M->__ValToPrg_Object:AFIELDS[2][1] := "COLUMN_"
         M->__ValToPrg_Object:AFIELDS[2][2] := "C"
         M->__ValToPrg_Object:AFIELDS[2][3] :=         50
         M->__ValToPrg_Object:AFIELDS[2][4] :=          0
         M->__ValToPrg_Object:AFIELDS[2][5] := .F.
         M->__ValToPrg_Object:AFIELDS[2][6] :=          1
         M->__ValToPrg_Object:AFIELDS[2][7] := NIL
         M->__ValToPrg_Object:AFIELDS[2][8] :=          2
         M->__ValToPrg_Object:AFIELDS[2][9] := NIL
         M->__ValToPrg_Object:AFIELDS[2][10] := NIL
         M->__ValToPrg_Object:AFIELDS[2][11] := NIL

      M->__ValToPrg_Object:AFIELDS[3] := Array(11)
         M->__ValToPrg_Object:AFIELDS[3][1] := "TYPE_"
         M->__ValToPrg_Object:AFIELDS[3][2] := "C"
         M->__ValToPrg_Object:AFIELDS[3][3] :=          1
         M->__ValToPrg_Object:AFIELDS[3][4] :=          0
         M->__ValToPrg_Object:AFIELDS[3][5] := .F.
         M->__ValToPrg_Object:AFIELDS[3][6] :=          1
         M->__ValToPrg_Object:AFIELDS[3][7] := NIL
         M->__ValToPrg_Object:AFIELDS[3][8] :=          3
         M->__ValToPrg_Object:AFIELDS[3][9] := NIL
         M->__ValToPrg_Object:AFIELDS[3][10] := NIL
         M->__ValToPrg_Object:AFIELDS[3][11] := NIL

      M->__ValToPrg_Object:AFIELDS[4] := Array(11)
         M->__ValToPrg_Object:AFIELDS[4][1] := "LEN_"
         M->__ValToPrg_Object:AFIELDS[4][2] := "C"
         M->__ValToPrg_Object:AFIELDS[4][3] :=          8
         M->__ValToPrg_Object:AFIELDS[4][4] :=          0
         M->__ValToPrg_Object:AFIELDS[4][5] := .F.
         M->__ValToPrg_Object:AFIELDS[4][6] :=          1
         M->__ValToPrg_Object:AFIELDS[4][7] := NIL
         M->__ValToPrg_Object:AFIELDS[4][8] :=          4
         M->__ValToPrg_Object:AFIELDS[4][9] := NIL
         M->__ValToPrg_Object:AFIELDS[4][10] := NIL
         M->__ValToPrg_Object:AFIELDS[4][11] := NIL

      M->__ValToPrg_Object:AFIELDS[5] := Array(11)
         M->__ValToPrg_Object:AFIELDS[5][1] := "DEC_"
         M->__ValToPrg_Object:AFIELDS[5][2] := "C"
         M->__ValToPrg_Object:AFIELDS[5][3] :=          8
         M->__ValToPrg_Object:AFIELDS[5][4] :=          0
         M->__ValToPrg_Object:AFIELDS[5][5] := .F.
         M->__ValToPrg_Object:AFIELDS[5][6] :=          1
         M->__ValToPrg_Object:AFIELDS[5][7] := NIL
         M->__ValToPrg_Object:AFIELDS[5][8] :=          5
         M->__ValToPrg_Object:AFIELDS[5][9] := NIL
         M->__ValToPrg_Object:AFIELDS[5][10] := NIL
         M->__ValToPrg_Object:AFIELDS[5][11] := NIL


   M->__ValToPrg_Object:HDBC := 0x3B5AF14
   M->__ValToPrg_Object:NRETCODE :=          0
   M->__ValToPrg_Object:NVERSION :=          1
   M->__ValToPrg_Object:OHASHACTIVEWAS := SQLFASTHASH():New()
      M->__ValToPrg_Object:OHASHACTIVEWAS:HHASH := Hash()

   M->__ValToPrg_Object:ATABLEINFO := Hash()
   M->__ValToPrg_Object:LRESULTSET := .F.
   M->__ValToPrg_Object:CLASTCOMM := "COMMIT
BEGIN"
   M->__ValToPrg_Object:CMGMNTVERS := "MGMNT 1.72          "
   M->__ValToPrg_Object:NID :=          1
   M->__ValToPrg_Object:OODBC := M->__ValToPrg_Object /* Cyclic */
   M->__ValToPrg_Object:NMILISECONDS :=          0.00
   M->__ValToPrg_Object:CPORT := 5432
   M->__ValToPrg_Object:CHOST := "localhost"
   M->__ValToPrg_Object:CDBS := ""
   M->__ValToPrg_Object:CDRV := ""
   M->__ValToPrg_Object:CDTB := "sm"
   M->__ValToPrg_Object:CNETLIBRARY := ""
